baseURL = 'https://www.danielmoch.com/'
languageCode = 'en-us'
title = "Daniel Moch's Web Home"
enableRobotsTXT = true
copyright = '© 2024 Daniel Moch'
disableKinds = ['taxonomy', 'term']

[services]
  [services.googleAnalytics]
    ID = 'G-KCNVPTFG6B'
  [services.rss]
    limit = 20

[params]
  [params.author]
    email = 'daniel@danielmoch.com'
    name = 'Daniel Moch'
  [[params.links]]
    text = 'Email'
    ref = 'mailto:daniel@danielmoch.com'
  [[params.links]]
    text = 'PGP'
    ref = '/static/gpg.asc'
  [[params.links]]
    text = 'Signify'
    ref = '/static/djmoch-signify.pub'
  [[params.links]]
    text = 'GitHub'
    ref = 'https://github.com/djmoch'
  [[params.links]]
    text = 'Mastodon'
    ref = 'https://discuss.systems/@djmoch'
  [[params.links]]
    text = 'Bluesky'
    ref = 'https://bsky.app/profile/danielmoch.com'
  [[params.links]]
    text = 'LinkedIn'
    ref = 'https://linkedin.com/in/djmoch'

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html']

[outputFormats]
  [outputFormats.rss]
    baseName = 'rss'
    isPlainText = false
    isHTML = false
    mediaType = 'application/rss+xml'
