baseURL = 'https://www.danielmoch.com/'
languageCode = 'en-us'
title = "Daniel Moch's Web Home"
enableRobotsTXT = true
copyright = '© 2024 Daniel Moch'

[taxonomies]
  category = 'categories'

[services]
  [services.googleAnalytics]
    ID = 'G-KCNVPTFG6B'
  [services.rss]
    limit = 20

[params]
  [params.author]
    email = 'daniel@danielmoch.com'
    name = 'Daniel Moch'
  [params.nav]
    [[params.nav.top]]
      text = 'Home'
      ref = '/'
    [[params.nav.top]]
      text = 'Posts'
      ref = '/posts/'
    [[params.nav.top]]
      text = 'Categories'
      ref = '/categories/'
    [[params.nav.top]]
      text = 'Git'
      ref = 'https://git.danielmoch.com'
    [[params.nav.top]]
      text = 'Resume'
      ref = '/resume/'
    [[params.nav.top]]
      text = 'PGP Key'
      ref = '/static/gpg.asc'
    [[params.nav.top]]
      text = 'Signify/Minisign Key'
      ref = '/static/djmoch-signify.pub'
    [[params.nav.top]]
      text = 'Colophon'
      ref = '/colophon/'
    [[params.nav.links]]
      text = 'fa-solid fa-envelope'
      ref = 'mailto:daniel@danielmoch.com'
    [[params.nav.links]]
      text = 'fa-brands fa-github'
      ref = 'https://github.com/djmoch'
    [[params.nav.links]]
      text = 'fa-brands fa-mastodon'
      ref = 'https://discuss.systems/@djmoch'
    [[params.nav.links]]
      text = 'fa-brands fa-bluesky'
      ref = 'https://bsky.app/profile/danielmoch.com'
    [[params.nav.links]]
      text = 'fa-brands fa-linkedin'
      ref = 'https://linkedin.com/in/djmoch'
    [[params.nav.links]]
      text = 'fa-brands fa-signal-messenger'
      ref = 'https://signal.me/#eu/g0NwS-dMpH0llD92SlVWoQXhkWoSCrEaHZIaFTfkWDTmqnSKLc1CtptpsMS6uPyp'

[privacy]
  [privacy.googleAnalytics]
    respectDoNotTrack = true

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html']

[outputFormats]
  [outputFormats.rss]
    baseName = 'rss'
    isPlainText = false
    isHTML = false
    mediaType = 'application/rss+xml'
